#!/usr/bin/python

import time
import io
import sys
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

number_of_arguments = len(sys.argv)

if number_of_arguments != 3:
    print "Error: need two arguments - URL and output file"
    quit()

url = sys.argv[1]
outfile = sys.argv[2]

driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub',
         desired_capabilities=DesiredCapabilities.CHROME)

driver.get(url);

time.sleep(10)

with io.open(outfile, encoding='utf-8', mode='w') as f:
    f.write(driver.page_source)
    f.close()

driver.quit()
